# Generated by Django 4.1.1 on 2022-10-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['user']},
        ),
    ]
